spring:
  datasource:
    url: jdbc:mysql://dahuo.cz7qdkmup07a.ap-northeast-1.rds.amazonaws.com:3306/dahuo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: admin
    password: dahuo123456
    driver-class-name: com.mysql.cj.jdbc.Driver

application:
  home:
    url: /dashboard
  logic:
    companyCd: 101
    url: http://127.0.0.1:8080/jsto-logic/graphql


